### ISSUE TITLE
what' mean about 'with local PostgreSQL server running'?

### ISSUE THREAD

**Issue by ivanberry** [realpython/flask-microservices-users#2]
Hi,
First, thank you for this awesome, I am stuck in [The part2, React Setup](http://testdriven.io/part-two-react-setup/). I am a newbie for back-end development and PostgreSQL. along with the turitus step by step, I always run the PostgreSQL by 
'docker-compose .....' stuff, but after refactoring the project into three isolated parts, how to 'run the local PostgreSQL locally', should I install PostgreSQL with brew first and then run it.

**Comment by mjhea0** [comment]
Yes.
