### ISSUE TITLE
Documentation update in Part 1 - Jinja Templates

### ISSUE THREAD

**Issue by stephencsnow** [realpython/flask-microservices-users#6]
Hey, really like the tutorial. Near the end of Part 1 of your guide, at the bottom of the [Jinja template section](http://testdriven.io/part-one-jinja-templates/), you instruct the audience to update the code on AWS via `docker-compose -f docker-compose-prod.yml up -d`. However, because you don't have the files mounted via a volume (therefore needing to rebuild on code changes), I believe that this should be `docker-compose -f docker-compose-prod.yml up -d --build`. Doing so caused my AWS instance to update properly.

**Comment by mjhea0** [comment]
Updated. Thank you!! :)
